name: Pull request to master

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint
        run: make lint
  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: make build
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: make test
publish:
  name: Publish docker image
  needs: test
  runs-on: ubuntu-latest
  env:
    DOCKER_USERNAME: ${{ secrets.JFROG_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: bin
        path: bin
    - name: build
      run: make image #tag: latest
    - name: publish
      run: make publish
